# -*- coding: utf-8 -*-
"""과제3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D_b3RW6sJXjtVYaUr4CeZtMusJYU5XDB
"""

import pandas as pd

df = pd.read_csv('/content/drive/My Drive/Korbit/[과제2] 2019-09 체결데이터_sample.csv')
df

import sqlite3

con = sqlite3.connect('/content/drive/My Drive/Korbit/trade.db')
type(con)
sqlite3.Connection

cursor = con.cursor()

cursor.execute("CREATE TABLE trade(action text, tx_type text, user_id int, currency text, trad_timestamp int)")

df.to_sql('trade', con)

from pandas import Series, DataFrame

df2 = pd.read_sql("SELECT * FROM trade", con, index_col=None)
df2 #sqlite로 연동 성공(db파일로 저장)

df3 = pd.read_sql("SELECT * FROM trade ORDER BY trade_timestamp DESC", con, index_col=None)

df3 # trade_timestamp 별로 내림차순

df4 = pd.read_sql("SELECT * FROM trade ORDER BY trade_timestamp DESC LIMIT 3", con, index_col=None)

df4 # 최근 3개 데이터

SELECT * FROM trade

WHERE (user_id, time) in (

    select user_id, max(time) FROM trade GROUP BY user_id

)

ORDER BY time DESC

df5 = pd.read_sql("SELECT * FROM trade WHERE (user_id, trade_timestamp) in (SELECT user_id, MAX(trade_timestamp) FROM trade GROUP BY user_id) ORDER BY trade_timestamp DESC", con, index_col=None)

df5 # 정답

